In [1]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\hyd\desktop\floodsentinels\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np

In [4]:
historical_df = pd.read_csv(
    "../data/raw/rainfall in india 1901-2015.csv"
)

district_df = pd.read_csv(
    "../data/raw/district wise rainfall normal.csv"
)

In [5]:
print("Historical Rainfall Dataset:")
print(historical_df.shape)

print("\nDistrict Rainfall Normal Dataset:")
print(district_df.shape)

Historical Rainfall Dataset:
(4116, 19)

District Rainfall Normal Dataset:
(641, 19)

In [6]:
historical_df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [7]:
district_df.head()

,STATE_UT_NAME,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN And NICOBAR ISLANDS,NICOBAR,107.3,57.9,65.2,117.0,358.5,295.5,285.0,271.9,354.8,326.0,315.2,250.9,2805.2,165.2,540.7,1207.2,892.1
1,ANDAMAN And NICOBAR ISLANDS,SOUTH ANDAMAN,43.7,26.0,18.6,90.5,374.4,457.2,421.3,423.1,455.6,301.2,275.8,128.3,3015.7,69.7,483.5,1757.2,705.3
2,ANDAMAN And NICOBAR ISLANDS,N & M ANDAMAN,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,454.8,276.1,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7
3,ARUNACHAL PRADESH,LOHIT,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
4,ARUNACHAL PRADESH,EAST SIANG,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,568.0,206.9,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1

In [8]:
print("Historical Dataset Columns:")
print(historical_df.columns.tolist())

print("\nDistrict Dataset Columns:")
print(district_df.columns.tolist())

Historical Dataset Columns:
['SUBDIVISION', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec']

District Dataset Columns:
['STATE_UT_NAME', 'DISTRICT', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec']

In [9]:
historical_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4112 non-null   float64
 3   FEB          4113 non-null   float64
 4   MAR          4110 non-null   float64
 5   APR          4112 non-null   float64
 6   MAY          4113 non-null   float64
 7   JUN          4111 non-null   float64
 8   JUL          4109 non-null   float64
 9   AUG          4112 non-null   float64
 10  SEP          4110 non-null   float64
 11  OCT          4109 non-null   float64
 12  NOV          4105 non-null   float64
 13  DEC          4106 non-null   float64
 14  ANNUAL       4090 non-null   float64
 15  Jan-Feb      4110 non-null   float64
 16  Mar-May      4107 non-null   float64
 17  Jun-Sep      4106 non-null   float64
 18  Oct-Dec      4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

In [10]:
district_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641 entries, 0 to 640
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   STATE_UT_NAME  641 non-null    object
 1   DISTRICT       641 non-null    object
 2   JAN            641 non-null    float64
 3   FEB            641 non-null    float64
 4   MAR            641 non-null    float64
 5   APR            641 non-null    float64
 6   MAY            641 non-null    float64
 7   JUN            641 non-null    float64
 8   JUL            641 non-null    float64
 9   AUG            641 non-null    float64
 10  SEP            641 non-null    float64
 11  OCT            641 non-null    float64
 12  NOV            641 non-null    float64
 13  DEC            641 non-null    float64
 14  ANNUAL         641 non-null    float64
 15  Jan-Feb        641 non-null    float64
 16  Mar-May        641 non-null    float64
 17  Jun-Sep        641 non-null    float64
 18  Oct-Dec        641 non-null    float64
dtypes: float64(17), object(2)
memory usage: 95.3+ KB

In [11]:
print("Missing values in Historical Dataset:")
print(historical_df.isnull().sum())

Missing values in Historical Dataset:
SUBDIVISION     0
YEAR            0
JAN             4
FEB             3
MAR             6
APR             4
MAY             3
JUN             5
JUL             7
AUG             4
SEP             6
OCT             7
NOV            11
DEC            10
ANNUAL         26
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [12]:
print("Missing values in District Dataset:")
print(district_df.isnull().sum())

Missing values in District Dataset:
STATE_UT_NAME    0
DISTRICT         0
JAN              0
FEB              0
MAR              0
APR              0
MAY              0
JUN              0
JUL              0
AUG              0
SEP              0
OCT              0
NOV              0
DEC              0
ANNUAL           0
Jan-Feb          0
Mar-May          0
Jun-Sep          0
Oct-Dec          0
dtype: int64

In [13]:
print("Historical Dataset Duplicates:")
print(historical_df.duplicated().sum())

Historical Dataset Duplicates:
0

In [14]:
print("District Dataset Duplicates:")
print(district_df.duplicated().sum())

District Dataset Duplicates:
0

In [15]:
historical_df.duplicated().sum()

np.int64(0)

In [16]:
district_df.duplicated().sum()

np.int64(0)

In [17]:
print("Minimum Year:", historical_df["YEAR"].min())
print("Maximum Year:", historical_df["YEAR"].max())

Minimum Year: 1901
Maximum Year: 2015

In [18]:
print("Number of unique years:", historical_df["YEAR"].nunique())

Number of unique years: 115

In [19]:
historical_df["YEAR"].value_counts().sort_index().head(10)

YEAR
1901    35
1902    35
1903    35
1904    35
1905    35
1906    35
1907    35
1908    35
1909    34
1910    35
Name: count, dtype: int64

In [20]:
historical_df["YEAR"].value_counts().sort_index().tail(10)

YEAR
2006    36
2007    36
2008    36
2009    36
2010    36
2011    36
2012    36
2013    36
2014    36
2015    36
Name: count, dtype: int64

In [21]:
print("Minimum Year:", historical_df["YEAR"].min())
print("Maximum Year:", historical_df["YEAR"].max())
print("Number of Unique Years:", historical_df["YEAR"].nunique())

Minimum Year: 1901
Maximum Year: 2015
Number of Unique Years: 115

In [22]:
expected_years = historical_df["YEAR"].max() - historical_df["YEAR"].min() + 1

print("Expected consecutive years:", expected_years)
print("Actual unique years:", historical_df["YEAR"].nunique())

Expected consecutive years: 115
Actual unique years: 115

In [24]:
year_counts = (
    historical_df
    .groupby("SUBDIVISION")["YEAR"]
    .nunique()
    .sort_values()
)

year_counts

SUBDIVISION
ARUNACHAL PRADESH                      97
ANDAMAN & NICOBAR ISLANDS             110
LAKSHADWEEP                           114
ASSAM & MEGHALAYA                     115
CHHATTISGARH                          115
COASTAL ANDHRA PRADESH                115
COASTAL KARNATAKA                     115
BIHAR                                 115
EAST RAJASTHAN                        115
EAST UTTAR PRADESH                    115
GANGETIC WEST BENGAL                  115
GUJARAT REGION                        115
HARYANA DELHI & CHANDIGARH            115
HIMACHAL PRADESH                      115
JAMMU & KASHMIR                       115
EAST MADHYA PRADESH                   115
JHARKHAND                             115
KERALA                                115
KONKAN & GOA                          115
MADHYA MAHARASHTRA                    115
MATATHWADA                            115
NAGA MANI MIZO TRIPURA                115
NORTH INTERIOR KARNATAKA              115
ORISSA                                115
PUNJAB                                115
RAYALSEEMA                            115
SAURASHTRA & KUTCH                    115
SOUTH INTERIOR KARNATAKA              115
SUB HIMALAYAN WEST BENGAL & SIKKIM    115
TAMIL NADU                            115
TELANGANA                             115
UTTARAKHAND                           115
VIDARBHA                              115
WEST MADHYA PRADESH                   115
WEST RAJASTHAN                        115
WEST UTTAR PRADESH                    115
Name: YEAR, dtype: int64

In [25]:
year_counts.value_counts().sort_index()

YEAR
97      1
110     1
114     1
115    33
Name: count, dtype: int64

In [26]:
incomplete_subdivisions = year_counts[year_counts < 115]

print("Subdivisions with incomplete year records:")
print(incomplete_subdivisions)

Subdivisions with incomplete year records:
SUBDIVISION
ARUNACHAL PRADESH             97
ANDAMAN & NICOBAR ISLANDS    110
LAKSHADWEEP                  114
Name: YEAR, dtype: int64

In [27]:
year_counts < 115

SUBDIVISION
ARUNACHAL PRADESH                      True
ANDAMAN & NICOBAR ISLANDS              True
LAKSHADWEEP                            True
ASSAM & MEGHALAYA                     False
CHHATTISGARH                          False
COASTAL ANDHRA PRADESH                False
COASTAL KARNATAKA                     False
BIHAR                                 False
EAST RAJASTHAN                        False
EAST UTTAR PRADESH                    False
GANGETIC WEST BENGAL                  False
GUJARAT REGION                        False
HARYANA DELHI & CHANDIGARH            False
HIMACHAL PRADESH                      False
JAMMU & KASHMIR                       False
EAST MADHYA PRADESH                   False
JHARKHAND                             False
KERALA                                False
KONKAN & GOA                          False
MADHYA MAHARASHTRA                    False
MATATHWADA                            False
NAGA MANI MIZO TRIPURA                False
NORTH INTERIOR KARNATAKA              False
ORISSA                                False
PUNJAB                                False
RAYALSEEMA                            False
SAURASHTRA & KUTCH                    False
SOUTH INTERIOR KARNATAKA              False
SUB HIMALAYAN WEST BENGAL & SIKKIM    False
TAMIL NADU                            False
TELANGANA                             False
UTTARAKHAND                           False
VIDARBHA                              False
WEST MADHYA PRADESH                   False
WEST RAJASTHAN                        False
WEST UTTAR PRADESH                    False
Name: YEAR, dtype: bool

In [28]:
all_years = set(range(1901, 2016))

for subdivision in incomplete_subdivisions.index:
    available_years = set(
        historical_df.loc[
            historical_df["SUBDIVISION"] == subdivision,
            "YEAR"
        ]
    )

    missing_years = sorted(all_years - available_years)

    print("\nSubdivision:", subdivision)
    print("Missing years:", missing_years)

Subdivision: ARUNACHAL PRADESH
Missing years: [1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1954, 1955, 1956]

Subdivision: ANDAMAN & NICOBAR ISLANDS
Missing years: [1909, 1943, 1944, 1945, 1948]

Subdivision: LAKSHADWEEP
Missing years: [1918]

In [29]:
historical_missing_percent = (
    historical_df.isnull().mean() * 100
).round(2)

historical_missing_percent

SUBDIVISION    0.00
YEAR           0.00
JAN            0.10
FEB            0.07
MAR            0.15
APR            0.10
MAY            0.07
JUN            0.12
JUL            0.17
AUG            0.10
SEP            0.15
OCT            0.17
NOV            0.27
DEC            0.24
ANNUAL         0.63
Jan-Feb        0.15
Mar-May        0.22
Jun-Sep        0.24
Oct-Dec        0.32
dtype: float64

In [30]:
rainfall_columns = [
    "JAN", "FEB", "MAR", "APR", "MAY", "JUN",
    "JUL", "AUG", "SEP", "OCT", "NOV", "DEC",
    "ANNUAL", "Jan-Feb", "Mar-May", "Jun-Sep", "Oct-Dec"
]

negative_counts = (historical_df[rainfall_columns] < 0).sum()

negative_counts

JAN        0
FEB        0
MAR        0
APR        0
MAY        0
JUN        0
JUL        0
AUG        0
SEP        0
OCT        0
NOV        0
DEC        0
ANNUAL     0
Jan-Feb    0
Mar-May    0
Jun-Sep    0
Oct-Dec    0
dtype: int64

In [31]:
district_negative_counts = (district_df[rainfall_columns] < 0).sum()

district_negative_counts

JAN        0
FEB        0
MAR        0
APR        0
MAY        0
JUN        0
JUL        0
AUG        0
SEP        0
OCT        0
NOV        0
DEC        0
ANNUAL     0
Jan-Feb    0
Mar-May    0
Jun-Sep    0
Oct-Dec    0
dtype: int64

In [32]:
historical_df[rainfall_columns].describe()

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4112.000000,4113.000000,4110.000000,4112.000000,4113.000000,4111.000000,4109.000000,4112.000000,4110.000000,4109.000000,4105.000000,4106.000000,4090.000000,4110.000000,4107.000000,4106.000000,4103.000000
mean,18.957320,21.805325,27.359197,43.127432,85.745417,230.234444,347.214334,290.263497,197.361922,95.507009,39.866163,18.870580,1411.008900,40.747786,155.901753,1064.724769,154.100487
std,33.585371,35.909488,46.959424,67.831168,123.234904,234.710758,269.539667,188.770477,135.408345,99.519134,68.685410,42.369611,903.846565,59.308277,201.316965,707.741531,166.942660
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,0.600000,0.600000,1.000000,3.000000,8.600000,70.350000,175.600000,155.975000,100.525000,14.600000,0.700000,0.100000,804.500000,4.100000,24.050000,573.850000,34.200000
50%,6.000000,6.700000,7.800000,15.700000,36.600000,138.700000,284.800000,259.400000,173.900000,65.200000,9.500000,3.000000,1121.300000,19.200000,74.800000,881.100000,98.200000
75%,22.200000,26.800000,31.300000,49.950000,97.200000,305.150000,418.400000,377.800000,265.800000,148.400000,46.100000,17.500000,1644.775000,50.375000,196.950000,1288.175000,213.500000
max,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000

In [33]:
district_df[rainfall_columns].describe()

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.00000,641.000000
mean,18.355070,20.984399,30.034789,45.543214,81.535101,196.007332,326.033697,291.152262,194.609048,90.446334,34.117473,18.150858,1346.969579,39.339470,157.113105,1007.80234,142.714665
std,21.082806,27.729596,45.451082,71.556279,111.960390,196.556284,221.364643,152.647325,99.830540,74.990685,59.371274,32.711009,838.878874,47.212773,213.445888,629.33261,148.951752
min,0.000000,0.000000,0.000000,0.000000,0.900000,3.800000,11.600000,14.100000,8.600000,3.100000,1.200000,0.000000,94.600000,0.000000,1.500000,39.60000,5.600000
25%,6.900000,7.000000,7.000000,5.000000,12.100000,68.800000,206.400000,194.600000,128.800000,34.300000,6.600000,5.300000,830.400000,14.700000,27.800000,625.40000,51.600000
50%,13.300000,12.300000,12.700000,15.100000,33.900000,131.900000,293.700000,284.800000,181.300000,62.600000,12.900000,7.900000,1116.200000,27.700000,67.200000,896.60000,86.700000
75%,19.200000,24.100000,33.200000,48.300000,91.900000,226.600000,374.800000,358.100000,234.100000,130.200000,32.300000,14.900000,1530.900000,41.100000,172.400000,1193.80000,175.200000
max,144.500000,229.600000,367.900000,554.400000,733.700000,1476.200000,1820.900000,1522.100000,826.300000,517.700000,475.100000,297.700000,7229.300000,335.300000,1256.500000,5228.00000,1048.500000

In [34]:
Q1 = historical_df[rainfall_columns].quantile(0.25)
Q3 = historical_df[rainfall_columns].quantile(0.75)

IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

outlier_counts = (
    historical_df[rainfall_columns] > upper_bound
).sum()

outlier_counts

JAN        387
FEB        393
MAR        467
APR        452
MAY        519
JUN        307
JUL        290
AUG        136
SEP        121
OCT        109
NOV        461
DEC        526
ANNUAL     396
Jan-Feb    357
Mar-May    411
Jun-Sep    297
Oct-Dec    236
dtype: int64

In [35]:
monthly_sum = historical_df[
    ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
     "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
].sum(axis=1, min_count=1)

difference = historical_df["ANNUAL"] - monthly_sum

difference.describe()

count    4090.000000
mean        0.002200
std         0.098906
min        -0.300000
25%        -0.100000
50%         0.000000
75%         0.100000
max         0.400000
dtype: float64